# Generated by Django 5.2.16 on 2026-07-15 21:05

from django.db import migrations

def seed_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('email_service', 'EmailTemplate')
    default_templates = [
        {
            'title': 'Employee Welcome & Onboarding',
            'subject': 'Welcome to the Team, {{first_name}}!',
            'message': 'Hi {{first_name}},\n\nWelcome to our organization! We are thrilled to have you join us as a {{designation}}.\n\nYour first week will be dedicated to onboarding, setting up your workstation, and introducing you to your new team members.\n\nIf you have any questions before your start date, please feel free to reach out.\n\nBest regards,\nHR Management Team'
        },
        {
            'title': 'Team Review Sync Meeting',
            'subject': 'Upcoming Team Review Sync Meeting Reminder',
            'message': 'Hi {{first_name}},\n\nThis is a quick reminder regarding our review meeting scheduled for tomorrow. Please be prepared with your reports and progress updates.\n\nWe will review the project milestones, address blockers, and align on next steps.\n\nBest,\nManagement'
        },
        {
            'title': 'Monthly Performance Evaluation Checklist',
            'subject': 'Monthly Performance Evaluation Checklist Required',
            'message': 'Hi {{first_name}},\n\nYour monthly performance evaluation checklist has been uploaded. Please review it and complete your self-evaluation by Friday.\n\nYour manager will then schedule a one-on-one session to discuss your feedback.\n\nBest regards,\nOperations Team'
        }
    ]
    for t in default_templates:
        EmailTemplate.objects.get_or_create(
            title=t['title'],
            defaults={'subject': t['subject'], 'message': t['message']}
        )

def remove_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('email_service', 'EmailTemplate')
    EmailTemplate.objects.filter(title__in=[
        'Employee Welcome & Onboarding',
        'Team Review Sync Meeting',
        'Monthly Performance Evaluation Checklist'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("email_service", "0002_emailtemplate"),
    ]

    operations = [
        migrations.RunPython(seed_templates, reverse_code=remove_templates),
    ]
