# Generated by Django 5.2.16 on 2026-07-15 07:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="employee",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="department.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.CharField(
                choices=[
                    ("SE", "Software Engineer"),
                    ("SSE", "Senior Software Engineer"),
                    ("MGR", "Manager"),
                    ("HR", "HR Executive"),
                    ("INT", "Intern"),
                    ("OTH", "Other"),
                ],
                default="SE",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="employee_id must match the pattern EMP followed by 3-6 digits (e.g. EMP001).",
                        regex="^EMP\\d{3,6}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 10-15 digits, optionally starting with '+'.",
                        regex="^\\+?\\d{10,15}$",
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["employee_id"], name="employee_em_employe_6b5233_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["email"], name="employee_em_email_9e89e3_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["department", "status"], name="employee_em_departm_6554b8_idx"
            ),
        ),
    ]
